n = input('Digite um algo: ')
print(type(n))
print("É númerico?", n.isnumeric())
print("É alfabético??", n.isalpha())
print("Só tem espaços?", n.isspace())
print("É alfanúmerico?", n.isalnum())
print("Tem maiúsculas?", n.isupper())
print("Tem minusculas?", n.islower())
print("Está capitalizada?", n.istitle())